trigger:
- main

pool:
  name: Localhost
  demands:
    - maven
    - docker

variables:
  - group: test


jobs:

###### BuildAndTest ###################################################################################################################################

- job: BuildAndTest
  displayName: Build and Test Spring Boot App
  
  steps:

  # Tests and then builds the maven project.
  - task: Maven@3
    inputs:
      mavenPomFile: backend/pom.xml
      goals: clean package
      javaHomeOption: JDKVersion
      mavenVersionOption: Default
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    env:
      DATABASE_URL: "localhost"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"

###### Dockerize ######################################################################################################################################

- job: Dockerize
  displayName: Dockerize the spring boot application jar file
  dependsOn: BuildAndTest
  
  steps:
  - checkout: none

  # Creates a docker image and then runs a container.
  - task: Docker@2
    inputs:
      repository: ams-backend
      command: build
      Dockerfile: backend/Dockerfile
      tags: latest

  # Runs a docker container with the image created above.
  - script: |
      docker run --name ams-backend -d -p 8080:8080 -e DATABASE_URL=ams-db -e DATABASE_USERMAME=root -e DATABASE_PASSWORD=root --network ams-network ams-backend:latest
    displayName: Run Docker container

###### InstallNewmanAndRunPostmanTests #################################################################################################################

- job: InstallNewmanAndRunPostmanTests
  dependsOn: Dockerize
  displayName: 'Execute Postman Tests'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '21.7.1'
    displayName: 'Install Node.js'
  
  - powershell: npm install -g newman newman-reporter-htmlextra
    displayName: 'Install Newman and HTML Extra Reporter'

  - powershell: |
      New-Item -ItemType Directory -Force -Path "$(Build.SourcesDirectory)\TestResults"
    displayName: 'Create Results Directory'

  - script: |
      newman run collection.json --reporters cli,junit,htmlextra ^
      --reporter-junit-export "$(Build.SourcesDirectory)\TestResults\testResults.xml" ^
      --reporter-htmlextra-export "$(Build.SourcesDirectory)\TestResults\testResults.html"
    displayName: 'Run Newman with Postman Collection for Reports'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Build.SourcesDirectory)/TestResults/testResults.xml'
      searchFolder: '$(Build.SourcesDirectory)\TestResults'
      failTaskOnFailedTests: true
      testRunTitle: 'Postman Test Results'
    displayName: 'Publish Postman Test Results'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\TestResults'
      ArtifactName: 'Postman Test Results'
      publishLocation: 'Container'
    displayName: 'Publish Newman Test Results as Artifact'

###### BuildReactApp #####################################################################################################################################

- job: BuildReactApp
  displayName: builds and creates a docker image of the react application
  dependsOn: InstallNewmanAndRunPostmanTests

  steps:
  - checkout: none

  - script: |
      cd frontend
      npm install
    displayName: Install node.js dependencies

  - script: |
      cd frontend
      npm run build
    displayName: Builds the react application

  - script: |
      cd frontend
      docker build -t ams-nginx .
    displayName: Dockerize react/nginx

###### PushDockerImages #############################################################################################################################

- job: PushDockerImages
  displayName: Pushes images to private container registry
  dependsOn: BuildReactApp
  
  steps:
  - checkout: none

  # Logs into the private container registry via a source connection
  - task: Docker@2
    displayName: Login to Azure Container Registry
    inputs:
      command: login
      containerRegistry: ams-acr

  # Tags the images for pushing them to the private repository in the cloud.
  # Latest tag overwrites the last latest image, so that the staging server can pull this.
  - script: |
      docker tag ams-backend amsprojectacr.azurecr.io/ams-backend:latest
      docker tag ams-nginx amsprojectacr.azurecr.io/ams-nginx:latest
    displayName: Tag Docker Image

  # Pushes the images to the registry.
  - script: |
        docker push amsprojectacr.azurecr.io/ams-backend:latest
        docker push amsprojectacr.azurecr.io/ams-nginx:latest
    displayName: Push Docker Image

####### Deploy ##########################################################################################################################################

- job: Deploy
  displayName: Deploys the docker to a cloud hosted staging server
  dependsOn: PushDockerImages

  steps:
  #- checkout: none

  # Logs into Azure via a service connection, and tears down the staging server if it exists.
  - task: AzureCLI@2
    displayName: Tear down current VM
    inputs:
      azureSubscription: ams-rm
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        az vm delete --name ams-vm --resource-group ams --yes
        az disk delete --name ams-vm --resource-group ams --yes

  # Deploys a new VM via the VMtemplate.json, it then sets itself up by downloading 
  # docker and azure cli for pulling and running the latest image via a custom script.
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Create new VM
    inputs:
      azureResourceManagerConnection: ams-rm
      subscriptionId: 77b69bf5-7cdb-462f-a4b2-b88204db74db
      resourceGroupName: ams
      location: Norway East
      csmFile: $(Build.SourcesDirectory)/VMtemplate.json
      deploymentMode: Incremental
      deploymentName: ams

####### Clean ##########################################################################################################################################

# Clean always runs wether the pipeline fails or not.
# Deletes the docker images built, and running docker containers.
- job: Clean
  displayName: Clean docker
  dependsOn: 
    #- BuildAndTest
    #- Dockerize
    - Deploy
  condition: always()

  steps:
  # Deletes the docker image.
  - script: |
        docker rm --force ams-backend
    displayName: Deletes the running container

  # Deletes the docker container.
  - script: |
      docker rmi ams-backend:$(Build.SourceVersion)
    displayName: Remove docker image on agent